DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'rag') THEN
    CREATE ROLE rag WITH LOGIN PASSWORD 'rag';
  END IF;
END
$$;

GRANT ALL PRIVILEGES ON DATABASE high_accuracy_rag TO rag;
